Category
tomczykp/io-opinion-collector pull request #10
Opened 2022-12-10 16:03 UTC by alice4book

category  class

2022-12-10 16:37 UTC, tomczykp requested changes
Managery są źle troszkę
Korzystamy ze Spring'a no i warstwy najlepiej dać
Zobacz np. jak chłopaki z Product zrobili albo z User,
Mają klasy modelu (u Was Category i Field, są w miarę dobrze), później Repository i dalej Manager i na końcu Controller (tutaj wystawia się endpointy dla połączenia backend-frontend)

2022-12-11 17:13 UTC, tomczykp requested changes
U mnie nie kompiluje/deploy się aplikacja, brakuje w klasach modelu adnotacji
I pare innych zmian potrzeba

2022-12-11 17:13 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/CategoryController.java
> +    @PutMapping("/category")
Zmienić lepiej bazowy endpoint aka @PutMapping("")
Metody będą rozróżniać żądania do /category

2022-12-11 17:13 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/FieldController.java
> +    @PutMapping("/field")
Analogicznie jak w CategoryController

2022-12-11 17:13 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/Category.java
> +
Brakuje paru adnotacji 
@Data
@Entity
@Valid
@NoArgsConstructor

2022-12-11 17:13 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/Field.java
> +
Jak w Category brakuje adnotacji do bazy danych

2022-12-12 01:11 UTC, tomczykp approved these changes
basic but looks good
getter/setters w klasach modelu raczej niekonieczne

2022-12-12 01:16 UTC, tomczykp commented
Sugestia zmian dla spójności i dobrych praktyk:
- endpointy są w liczbie mnogiej u nas /api/categories
- korzystać z DTO
- mock dane dodać (jakieś przykładowe dane do SQL dopisać)

2022-12-12 01:26 UTC, tomczykp requested changes
Nie zauważyłem wcześniej 
Endpoint są źle, korzystaj z DTO najlepiej
A tutaj masz PathVariable a w ścieżce nie masz żadnych zmiennych

2022-12-12 01:26 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/FieldController.java
> +    public Field createField(@PathVariable String name, @PathVariable Class type){
PathVariable ke?

2022-12-12 01:26 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/CategoryController.java
> +    public Category createCategory(@PathVariable String name, @PathVariable List<Field> fields ){
PathVariable ke?
Wykorzystaj DTO najlepiej

2022-12-12 01:26 UTC, tomczykp commented on backend/src/main/java/pl/lodz/p/it/opinioncollector/category/CategoryController.java
> +    public Category modifyCategory(Category category, String name, List<Field> fields){
Tutaj brakuje w ogóle skąd są parametry funkcji

2022-12-14 13:52 UTC, tomczykp requested changes
Nie wrzucaj plików od IDE, dodaj do gitignore
A dalej nie ma DTO ani też nie Field nie działą jak powinno, nie można zdeserializować Class z JSON albo String przychodzących w Request'ie

2022-12-18 17:05 UTC, St0n3k approved these changes
Ok

2022-12-18 17:08 UTC, tomczykp approved these changes
good

2022-12-18 17:08 UTC, merged